Add     "too_many_images_upload"
LemmyNet/lemmy-translations pull request #28
Opened 2022-10-03 18:11 UTC by sam365724

2022-10-03 18:19 UTC, dessalines requested changes

2022-10-03 18:19 UTC, dessalines commented on translations/en.json
> +    "too_many_images_upload": "Maximum number of images to upload: 20. Please select fewer images.",
Don't hardcode that number, use either a generic message, or one with a count as shown below.

2022-10-07 09:54 UTC, sam365724 commented on translations/en.json
> +    "too_many_images_upload": "Maximum number of images to upload: 20. Please select fewer images.",
Good idea, will put the max into the message.

2022-10-07 16:25 UTC, dessalines commented on translations/en.json
> +    "too_many_images_upload": "Exceeded maximum of {maxFormatted} images to upload. Please select fewer images.",
Did you look in this file to see how other plurals work?

2022-10-12 10:15 UTC, sam365724 commented on translations/en.json
> +    "too_many_images_upload": "Exceeded maximum of {maxFormatted} images to upload. Please select fewer images.",
We don't need the plural here. I think we always allow more than 1 image to be uploaded?! Default is 20. If you insist i'd change to this: 

```
    "too_many_images_upload": "Exceeded maximum of {maxFormatted} image to upload. Please select only one image.",
    "too_many_images_upload_plural": "Exceeded maximum of {maxFormatted} images to upload. Please select fewer images.",
```

2022-10-13 00:24 UTC, dessalines commented on translations/en.json
> +    "too_many_images_upload": "Exceeded maximum of {maxFormatted} images to upload. Please select fewer images.",
"Exceeded maximum number of **1 images** to upload.

Please look in this file for how other plurals work with count.

2022-10-13 09:54 UTC, sam365724 commented on translations/en.json
> +    "too_many_images_upload": "Exceeded maximum of {maxFormatted} images to upload. Please select fewer images.",
I did look into it. Is the proposal from above fine with _plural?

2022-10-13 10:04 UTC, sam365724 commented on translations/en.json
> +    "too_many_images_upload": "Exceeded maximum of {maxFormatted} images to upload. Please select fewer images.",
@dessalines This ok? https://github.com/LemmyNet/lemmy-ui/pull/812/commits/692d8a2336c22e85ad7d0866da236b0886179f00

2022-10-13 12:35 UTC, dessalines requested changes

2022-10-13 12:35 UTC, dessalines commented on translations/en.json
> +    "too_many_images_upload_plural": "Exceeded maximum of {maxFormatted} images to upload. Please select fewer images.",
Look at the other plural lines in this file. They use two braces.

2022-10-13 22:55 UTC, dessalines approved these changes

2022-10-13 22:55 UTC, merged